resolver: nightly-2017-09-18

packages:
- ./.

extra-deps:
- strptime-1.0.10
- vcs-revision-0.0.2
- splot-0.3.14

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

nix:
  shell-file: shell.nix
